# Project Name
TARGET = ADSR_V2
APP_TYPE = BOOT_QSPI
USE_FATFS = 1

C_INCLUDES += -I.
C_INCLUDES += -I./src/ui
C_INCLUDES += -I./src/worker
C_INCLUDES += -I./src/storage

# Sources
CPP_SOURCES = main.cpp
CPP_SOURCES += audio_callback.cpp
CPP_SOURCES += params.cpp
CPP_SOURCES += tilt_eq.cpp
CPP_SOURCES += audio_engine.cpp
CPP_SOURCES += src/ui/ui_logic.cpp
CPP_SOURCES += src/ui/ui_render.cpp
CPP_SOURCES += src/ui/ui_input.cpp
CPP_SOURCES += controls.cpp
CPP_SOURCES += ui_screens.cpp
CPP_SOURCES += src/ui/ui_router.cpp
CPP_SOURCES += src/ui/ui_screen_registry.cpp
CPP_SOURCES += src/ui/ui_draw_text.cpp
CPP_SOURCES += src/ui/ui_draw_shapes.cpp
CPP_SOURCES += src/ui/ui_draw_controls.cpp
CPP_SOURCES += src/ui/ui_screen_main.cpp
CPP_SOURCES += src/ui/ui_screen_hud.cpp
CPP_SOURCES += src/ui/ui_screen_fx.cpp
CPP_SOURCES += src/ui/ui_screen_mod.cpp
CPP_SOURCES += src/ui/ui_screen_macro.cpp
CPP_SOURCES += src/ui/ui_screen_shift.cpp
CPP_SOURCES += src/ui/ui_screen_record.cpp
CPP_SOURCES += src/ui/ui_screen_record_event.cpp
CPP_SOURCES += src/ui/ui_screen_perform_menu.cpp
CPP_SOURCES += src/ui/ui_screen_perform_engine.cpp
CPP_SOURCES += src/ui/ui_screen_perform_wave_edit.cpp
CPP_SOURCES += src/ui/ui_screen_perform_keyzone.cpp
CPP_SOURCES += src/ui/ui_screen_perform_adsr.cpp
CPP_SOURCES += src/ui/ui_screen_perform_adsr_edit.cpp
CPP_SOURCES += src/ui/ui_screen_perform_adsr_render.cpp
CPP_SOURCES += src/ui/ui_screen_perform_emphasis.cpp
CPP_SOURCES += src/ui/ui_screen_perform_process.cpp
CPP_SOURCES += src/ui/ui_screen_perform_process_edit.cpp
CPP_SOURCES += src/ui/ui_screen_perform_process_render.cpp
CPP_SOURCES += src/ui/ui_screen_perform_process_draw.cpp
CPP_SOURCES += src/ui/ui_screen_status.cpp
CPP_SOURCES += src/ui/ui_screen_sd_browse.cpp
CPP_SOURCES += src/ui/ui_screen_sd_delete_confirm.cpp
CPP_SOURCES += src/ui/ui_screen_sample_edit.cpp
CPP_SOURCES += src/ui/ui_list_menu.cpp
CPP_SOURCES += src/ui/ui_value_edit.cpp
CPP_SOURCES += src/ui/ui_layout.cpp
CPP_SOURCES += src/ui/ui_overlay.cpp
CPP_SOURCES += ui_requests.cpp
CPP_SOURCES += src/ui/project_actions.cpp
CPP_SOURCES += src/worker/ui_worker_sd_lifecycle.cpp
CPP_SOURCES += src/worker/ui_worker.cpp
CPP_SOURCES += src/worker/ui_worker_sd_scan.cpp
CPP_SOURCES += src/worker/ui_worker_sample_load.cpp
CPP_SOURCES += src/worker/ui_worker_sample_ops.cpp
CPP_SOURCES += src/worker/ui_worker_project.cpp
CPP_SOURCES += src/worker/ui_worker_project_load.cpp
CPP_SOURCES += src/worker/ui_worker_project_manifest.cpp
CPP_SOURCES += src/worker/ui_worker_wav.cpp
CPP_SOURCES += src/storage/sd_browser_state.cpp
CPP_SOURCES += src/storage/sd_sample_pool.cpp
CPP_SOURCES += src/ui/oled_pager.cpp
CPP_SOURCES += voice_engine.cpp
CPP_SOURCES += voice_engine_playback.cpp
CPP_SOURCES += voice_engine_emphasis.cpp
CPP_SOURCES += voice_engine_voice_lifecycle.cpp
CPP_SOURCES += voice_engine_events.cpp
CPP_SOURCES += voice_engine_render.cpp
CPP_SOURCES += voice_engine_render_voice.cpp
CPP_SOURCES += voice_engine_render_playback.cpp
CPP_SOURCES += voice_engine_render_loop.cpp
CPP_SOURCES += voice_engine_render_fetch.cpp
CPP_SOURCES += voice_engine_render_layer.cpp
CPP_SOURCES += keygroups.cpp
CPP_SOURCES += velocity_layers.cpp
CPP_SOURCES += mod_sources.cpp
CPP_SOURCES += mod_matrix.cpp
CPP_SOURCES += plocks.cpp
CPP_SOURCES += macros.cpp
CPP_SOURCES += Effects/Reverb/DattorroReverb.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
